trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  NODE_VERSION: '18.x'   # Next.js soporta Node 18 y 20

steps:
# 1. Checkout del repo
- task: Checkout@1
  inputs:
    fetchDepth: 1

# 2. Instalar Node
- task: UseNode@1
  inputs:
    versionSpec: $(NODE_VERSION)
    checkLatest: true

# 3. Instalar dependencias
- script: |
    npm install
  displayName: 'Instalar dependencias'

# 4. Build del proyecto
- script: |
    npm run build
  displayName: 'Build Next.js'

# 5. Exportar (solo si usas `next export`)
# Si es SSR, no lo pongas
- script: |
    npm run export
  displayName: 'Exportar sitio (static)'

# 6. Archivar para publicar
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)/out' # usa `.next` si no exportas
    includeRootFolder: false
    archiveType: zip
    archiveFile: $(Build.ArtifactStagingDirectory)/build.zip
    replaceExistingArchive: true

# 7. Publicar en artifacts (necesario para Release)
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
