trigger:
  branches:
    include:
      - main
      - qa

pool:
  name: 'PoolAgentDataCNE'

variables:
  QA_WEBAPP_NAME: "datacne-qa"
  PROD_WEBAPP_NAME: "DataCNE"
  NODE_VERSION: "20.x"

steps:
  # 1. Instalar Node.js
  - task: NodeTool@0
    inputs:
      versionSpec: "$(NODE_VERSION)"
    displayName: "Install Node.js"

  # 2. Instalar dependencias y compilar optimize-images.ts
  - script: |
      npm ci
      npm run build:ci
      npx tsc scripts/optimize-images.ts --esModuleInterop --target ES2019 --module commonjs --outDir scripts/build
      node scripts/build/optimize-images.js
    workingDirectory: "$(System.DefaultWorkingDirectory)"
    displayName: "Build Next.js static export"

  # 3. Empaquetar artefacto (carpeta out/)
  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: "$(System.DefaultWorkingDirectory)/out"
      includeRootFolder: false
      archiveType: zip
      archiveFile: "$(Build.ArtifactStagingDirectory)/app.zip"
      replaceExistingArchive: true
    displayName: "Create artifact ZIP"

  # 4. Deploy a QA slot (rama qa)
  - task: AzureWebApp@1
    condition: eq(variables['Build.SourceBranch'], 'refs/heads/qa')
    inputs:
      azureSubscription: "ConectDataCNE"
      appName: "$(QA_WEBAPP_NAME)"
      package: "$(Build.ArtifactStagingDirectory)/app.zip"
      slotName: "qa"
    displayName: "Deploy to QA slot"

  # 5. Deploy a producción (rama main)
  - task: AzureWebApp@1
    condition: eq(variables['Build.SourceBranch'], 'refs/heads/main')
    inputs:
      azureSubscription: "ConectDataCNE"
      appName: "$(PROD_WEBAPP_NAME)"
      package: "$(Build.ArtifactStagingDirectory)/app.zip"
    displayName: "Deploy to Production"
