trigger:
  branches:
    include:
      - main
      - qa

pool:
  vmImage: "ubuntu-latest"

variables:
  QA_WEBAPP_NAME: "datacne-qa"
  PROD_WEBAPP_NAME: "DataCNE"
  NODE_VERSION: "20.x"

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: "$(NODE_VERSION)"
    displayName: "Install Node.js"

  - script: |
      npm ci
      npm run build
    displayName: "Install & Build"

  # Empaquetar el build para desplegar
  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: "$(System.DefaultWorkingDirectory)"
      includeRootFolder: false
      archiveType: zip
      archiveFile: "$(Build.ArtifactStagingDirectory)/app.zip"
      replaceExistingArchive: true
    displayName: "Create artifact ZIP"

  # Deploy a slot QA (cuando la rama sea qa)
  - task: AzureWebApp@1
    condition: eq(variables['Build.SourceBranch'], 'refs/heads/qa')
    inputs:
      azureSubscription: "ConectDataCNE"    # <--- exactamente como lo nombraste en Service connections
      appName: "$(datacne-qa)"
      package: "$(Build.ArtifactStagingDirectory)/app.zip"
      slotName: "qa"                               # despliega al slot datacne-qa
    displayName: "Deploy to QA slot"

  # Deploy a producción (cuando la rama sea main)
  - task: AzureWebApp@1
    condition: eq(variables['Build.SourceBranch'], 'refs/heads/main')
    inputs:
      azureSubscription: "ConectDataCNE"
      appName: "$(DataCNE)"
      package: "$(Build.ArtifactStagingDirectory)/app.zip"
    displayName: "Deploy to Production"
