trigger:
  branches:
    include:
      - main   # producción
      - qa     # pruebas

pool:
  vmImage: ubuntu-latest

steps:
# 1. Instalar Node.js
- task: NodeTool@0
  inputs:
    versionSpec: '18.x'   # o la versión que uses (16.x, 20.x)
  displayName: 'Instalar Node.js'

# 2. Instalar dependencias
- script: |
    npm install
  displayName: 'Instalar dependencias'

# 3. Build
- script: |
    npm run build
  displayName: 'Compilar proyecto'

# 4. Publicar artefactos de build
- task: CopyFiles@2
  inputs:
    contents: |
      build/**         # CRA / Vite
      .next/**         # Next.js
    targetFolder: '$(Build.ArtifactStagingDirectory)'
  displayName: 'Copiar artefactos de build'

# 5. Deploy a Azure Web App
- task: AzureWebApp@1
  inputs:
    azureSubscription: 'CNE-PublishProfile'   # tu service connection
    appName: 'AppDataCNE'                     # nombre de tu Web App en Azure
    package: '$(Build.ArtifactStagingDirectory)'
  displayName: 'Deploy a Azure Web App'
