trigger:
  branches:
    include:
      - main
      - qa

pool:
  vmImage: 'ubuntu-latest'

variables:
  NODE_ENV: 'production'

stages:
  - stage: BuildAndDeploy
    displayName: 'Build & Deploy Next.js'
    jobs:
      - job: Build
        displayName: 'Build Next.js App'
        steps:
          # 1. Instalar Node.js
          - task: NodeTool@0
            inputs:
              versionSpec: '20.x'
            displayName: 'Data CNE Website'

          # 2. Instalar dependencias y construir
          - script: |
              npm install
              npm run build
            displayName: 'Install dependencies & Build Next.js'

          # 3. Desplegar a Azure Web App
          - task: AzureWebApp@1
            displayName: 'Deploy to Azure Web App'
            inputs:
              azureSubscription: '<TU_CONEXIÓN_A_AZURE>'
              appName: '$(WebAppName)'
              package: '$(System.DefaultWorkingDirectory)'
