trigger:
  branches:
    include:
      - main
      - qa

pool:
  vmImage: 'ubuntu-latest'

variables:
  QA_WEBAPP_NAME: "datacne-qa"
  PROD_WEBAPP_NAME: "DataCNE"
  NODE_VERSION: "20.x"

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: "$(NODE_VERSION)"
    displayName: "Install Node.js"

  - script: |
      npm ci
      npm run build
      npm run export
    displayName: "Build Next.js static export"

  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: "$(System.DefaultWorkingDirectory)/out"
      includeRootFolder: false
      archiveType: zip
      archiveFile: "$(Build.ArtifactStagingDirectory)/app.zip"
      replaceExistingArchive: true
    displayName: "Create artifact ZIP"

  # Deploy QA (slot)
  - task: AzureWebApp@1
    condition: eq(variables['Build.SourceBranch'], 'refs/heads/qa')
    inputs:
      azureSubscription: "ConectDataCNE" 
      appName: "$(QA_WEBAPP_NAME)"
      package: "$(Build.ArtifactStagingDirectory)/app.zip"
      slotName: "qa"
    displayName: "Deploy to QA slot"

  # Deploy Producción
  - task: AzureWebApp@1
    condition: eq(variables['Build.SourceBranch'], 'refs/heads/main')
    inputs:
      azureSubscription: "ConectDataCNE"
      appName: "$(PROD_WEBAPP_NAME)"
      package: "$(Build.ArtifactStagingDirectory)/app.zip"
    displayName: "Deploy to Production"
